# App
spring.application.name=paystream-api
server.port=8080

# PostgreSQL (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-muddy-king-aqws8uo1.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-muddy-king-aqws8uo1
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ovc9oluwIA6Z
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis (Upstash)
spring.data.redis.url=redis://default:gQAAAAAAAhmHAAIgcDFhMTVkNzg2N2UyMDY0NDcwYTcwNDJiOGI4NDUyYzk5NQ@crisp-turtle-137607.upstash.io:6379
spring.data.redis.ssl.enabled=true

# JWT
jwt.secret=myone-super-secret-key-which-is-minimum-256-bits-long-ok-ah
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=com.paystream.api.controller
# Enable debug logging for Swagger
logging.level.org.springdoc=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,metrics